from . import product
from . import pos_order
from . import sale
from . import purchase
from . import stock_move
from . import stock_move_line
from . import stock_rule
from . import account_move
from . import stock_picking
from . import stock_orderpoint
from . import stock_scrap
from . import stock_quant
